version: "3.8"

services:
  pipeline:
    build:
      context: ./pipeline
    image: mri-pipeline:latest
    container_name: mri-pipeline
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - orthanc

  orthanc:
    image: osimis/orthanc:24.4.0
    container_name: orthanc
    environment:
      # Default authentication for REST API
      ORTHANC__NAME: "Orthanc in Docker"
      ORTHANC__REGISTERED_USERS: |-
        {
          "orthanc": "orthanc"
        }
      # Enable/disable remote access control etc. Basic defaults here
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
    ports:
      - "8042:8042"  # HTTP REST API
      - "4242:4242"  # DICOM port
    volumes:
      - orthanc-storage:/var/lib/orthanc

volumes:
  orthanc-storage:
