services:
  pipeline:
    build:
      context: ./pipeline
    container_name: mri-pipeline
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - orthanc
      - triton

  orthanc:
    image: orthancteam/orthanc
    container_name: orthanc
    environment:
      ORTHANC__NAME: "Orthanc in Docker"
      ORTHANC__REGISTERED_USERS: |-
        {
          "orthanc": "orthanc"
        }
      ORTHANC__REMOTE_ACCESS_ALLOWED: "true"
    ports:
      - "8042:8042"  # HTTP REST API
      - "4242:4242"  # DICOM port
    volumes:
      - orthanc-storage:/var/lib/orthanc

  triton:
    image: nvcr.io/nvidia/tritonserver:24.05-py3
    container_name: triton
    command: tritonserver --model-repository=/models --backend-directory=/opt/tritonserver/backends --backend-config=python,shm-region-prefix-name=prefix1_
    volumes:
      - ./triton/model_repo:/models

volumes:
  orthanc-storage: